import express from 'express';
import { createServer } from 'http';
import { createServer as createHttpsServer } from 'https';
import fs from 'fs';
import path from 'path';
import { Server } from 'socket.io';
import { GunService } from './services/gun-service';
import { ChatroomManager } from './services/chatroom-manager';
import { TalkService } from './services/talk-service';
import { UserService } from './services/user-service';
import { ReputationService } from './services/reputation-service';
import { logger } from './logger';
import { attachGun, configureHttpMiddleware, createSocketServer } from './bootstrap/http-bootstrap';
import { registerChatroomRoutes } from './routes/chatroom-routes';
import { registerStatsRoutes } from './routes/stats-routes';
import { BroadcastTagPopularityStore } from './services/broadcast-tag-popularity-store';
import { registerSystemRoutes } from './routes/system-routes';
import { registerTalkRoutes } from './routes/talk-routes';
import { registerUserRoutes } from './routes/user-routes';
import { registerSocketHandlers } from './socket/register-socket-handlers';
import { MailboxStore } from './services/mailbox-store';
import { registerMailboxRoutes } from './routes/mailbox-routes';
import { TechSupportDurableStore } from './services/techsupport-durable-store';
import { registerTurnRoutes } from './routes/turn-routes';
import { registerAdminRoutes } from './routes/admin-routes';
import { TechSupportAnnouncementService } from './services/techsupport-announcement-service';
import { LanGunDiscovery } from './services/lan-gun-discovery';
import {
  inspectSchemaVersions,
  type SchemaKind,
} from '../shared/p2p-schema-migrations';
import { CHATROOM_HIERARCHY } from '../shared/chatroom-hierarchy';
import { resolveEmbeddedNodeConfig } from '../shared/embedded-node-config';
import { EmbeddedHubRelayClient } from '../node-app/embedded-hub-relay-client';
import { resolveTlsMode } from './tls-mode';

/**
 * Create the HTTP(S) server the app listens on.
 *
 * If a TLS certificate exists (certs/dev-*.pem, generated by
 * scripts/gen-dev-cert.sh, or TLS_KEY_PATH/TLS_CERT_PATH), serve over HTTPS so
 * LAN clients (phones/other PCs reaching this host by its 192.168.x.x address)
 * load in a secure context — required by Gun.js SEA / WebCrypto, and it stops
 * SEA from redirecting to a port that isn't listening. Hosted deployments may
 * declare IINPUBLIC_TLS_TERMINATED_BY_PROXY=1 when their edge proxy owns HTTPS.
 * There is no silent production fallback to plaintext.
 *
 * E2E servers must stay plain HTTP: every Playwright-spawned server runs with
 * E2E_GUN_MEMORY_ONLY=1 and the harness health-checks/clears over http://127.0.0.1
 * (helpers/clear-database.ts). With certs/ present on the dev machine, TLS here
 * turned every one of those requests into a handshake failure and failed the whole
 * suite ("waitForGunApiReady ... fetch failed"). TLS_DISABLE=1 is a manual escape hatch.
 */
function createAppServer(app: express.Application) {
  const keyPath = process.env.TLS_KEY_PATH || path.resolve(process.cwd(), 'certs/dev-key.pem');
  const certPath = process.env.TLS_CERT_PATH || path.resolve(process.cwd(), 'certs/dev-cert.pem');
  const tlsMode = resolveTlsMode(process.env, {
    keyExists: fs.existsSync(keyPath),
    certExists: fs.existsSync(certPath),
  });

  if (tlsMode === 'direct-https') {
    logger.info({ keyPath, certPath }, '🔒 HTTPS enabled');
    return createHttpsServer(
      { key: fs.readFileSync(keyPath), cert: fs.readFileSync(certPath) },
      app,
    );
  }
  if (tlsMode === 'https-proxy') {
    logger.info('🔒 HTTPS is terminated by the hosting proxy');
  } else if (tlsMode === 'plaintext-loopback') {
    logger.info('Plain HTTP enabled for loopback-only embedded app node');
  } else {
    logger.warn('Plain HTTP enabled for isolated test execution only');
  }
  return createServer(app);
}

class IinPublicServer {
  private app: express.Application;
  private server: any;
  private io: Server;
  private gun: any;
  private gunService!: GunService;
  private chatroomManager!: ChatroomManager;
  private talkService!: TalkService;
  private userService!: UserService;
  private reputationService!: ReputationService;
  private techSupportAnnouncements!: TechSupportAnnouncementService;
  private hubRelayClient?: EmbeddedHubRelayClient;
  private lanGunDiscovery?: LanGunDiscovery;

  private mailboxStore = new MailboxStore();
  private mailboxSweepTimer: ReturnType<typeof setInterval> | undefined;
  private techSupportStore = new TechSupportDurableStore();

  private broadcastTagPopularityStore = new BroadcastTagPopularityStore();

  constructor() {
    this.app = express();
    this.server = createAppServer(this.app);
    this.io = createSocketServer(this.server);

    this.setupMiddleware();
    this.setupGun();
    this.initializeServices();
    this.setupRoutes();
    this.setupSocketHandlers();
  }

  private setupGun(): void {
    this.gun = attachGun(this.server);
  }

  private setupMiddleware(): void {
    configureHttpMiddleware(this.app);
  }

  private initializeServices(): void {
    this.gunService = new GunService(this.gun); // Pass the Gun instance
    this.userService = new UserService(this.gunService);
    this.reputationService = new ReputationService(this.gunService);
    this.chatroomManager = new ChatroomManager(this.gunService);
    this.talkService = new TalkService(this.gunService, this.reputationService);
    this.techSupportAnnouncements = new TechSupportAnnouncementService(this.gunService);
    const embedded = resolveEmbeddedNodeConfig(process.env);
    if (
      embedded.enabled &&
      embedded.hubRelayMode === 'explicit-http' &&
      embedded.upstreamHubBaseUrl
    ) {
      this.hubRelayClient = new EmbeddedHubRelayClient({
        upstreamHubBaseUrl: embedded.upstreamHubBaseUrl,
      });
    }
    this.logStartupSchemaDiagnostics();
    void this.publishPublicBootstrap();
  }

  /**
   * Public, signed network metadata must exist after boot and after an E2E graph reset.
   *
   * K3 (docs/TODO.md): no longer gated on `techSupportAnnouncements.isConfigured()` — the
   * identity record is a committed, pre-signed blob (no private key needed at boot), and the
   * Global member-row seed is a plain Gun write (never needed a key). A relay with no
   * `TECHSUPPORT_SEA_PAIR_JSON` configured at all (the announcement pair is only needed for the
   * on-demand admin announcement feature) still produces a full, correct relay-light presence.
   */
  private async publishPublicBootstrap(): Promise<void> {
    this.gun.get('public').get('chatroom-hierarchy').put(JSON.stringify(CHATROOM_HIERARCHY));
    try {
      await this.techSupportAnnouncements.publishIdentity();
    } catch (error) {
      logger.error({ error }, 'Could not publish TechSupport identity');
    }
    // K1 item 2: the relay alone must produce headcount 2 in Global, with no browser ever
    // having bootstrapped. Best-effort like the identity publish above — a seed failure must
    // not crash boot; the client-side synthetic floor (K1 item 1) is the safety net.
    try {
      await this.chatroomManager.seedTechSupportGlobalMembership();
    } catch (error) {
      logger.error({ error }, 'Could not seed TechSupport Global membership');
    }
  }

  /**
   * P2P-X: Log schema-version diagnostics for in-memory record stores at
   * startup so operators can see whether pending migrations exist.
   * Runs synchronously; actual record migration happens on-read via migrateRecord.
   */
  private logStartupSchemaDiagnostics(): void {
    const kinds: SchemaKind[] = [
      'presence', 'peerOffer', 'catalogRecord', 'pairResponse', 'pairConversation',
      'knownPerson', 'neighborCache', 'ledgerEvent', 'localInIndex', 'localOutIndex',
      'peerTrustRecord', 'handshakeRecord',
    ];
    for (const kind of kinds) {
      // Server starts with empty in-memory maps; log zero pending as confirmation.
      const diag = inspectSchemaVersions(kind, []);
      if (diag.pendingMigrations > 0) {
        logger.info({ kind, pendingMigrations: diag.pendingMigrations, currentVersion: diag.currentVersion },
          'P2P-X: schema migration needed for stored records');
      }
    }
    logger.info({ kinds }, 'P2P-X: startup schema diagnostics complete');
  }

  private async loadTalkDataFromGraphOrBody(talkId: string, bodyTalkData?: unknown): Promise<any | null> {
    const parseBody = (): any | null => {
      if (bodyTalkData == null) return null;
      return typeof bodyTalkData === 'string' ? JSON.parse(bodyTalkData as string) : bodyTalkData;
    };

    const looksAuthoritative = (t: any): boolean => {
      if (!t || typeof t !== 'object') return false;
      const aid = t.authorId;
      if (aid == null || String(aid).trim() === '' || String(aid) === 'undefined') return false;
      // Tag talks have no questions — treat as authoritative if they have a title
      if (t.type === 'tag') return !!(t.title);
      const qs = t.questions;
      if (!Array.isArray(qs) || qs.length === 0) return false;
      return true;
    };

    const fromBody = parseBody();

    // Prefer authoritative POST body first: the sender includes full talk JSON for broadcast batches.
    // Skip the Gun.js graph lookup entirely when body is already authoritative (avoids event-loop stall).
    if (looksAuthoritative(fromBody)) return fromBody;

    let fromGraph: any | null = null;
    const rawTalk = await this.gunService.getPath(['talks', talkId]);
    if (rawTalk) {
      try {
        if (typeof rawTalk.data === 'string') {
          fromGraph = JSON.parse(rawTalk.data);
        } else {
          fromGraph = rawTalk.data || rawTalk;
        }
      } catch {
        fromGraph = null;
      }
    }

    if (looksAuthoritative(fromGraph)) return fromGraph;
    if (fromGraph) return fromGraph;
    return fromBody;
  }

  private clearForTesting(): void {
    this.broadcastTagPopularityStore.resetForTesting();
    this.mailboxStore.resetForTesting();
  }

  private setupRoutes(): void {
    registerSystemRoutes(this.app, {
      gun: this.gun,
      gunService: this.gunService,
      clearForTesting: this.clearForTesting.bind(this),
      onClearDatabase: async () => {
        this.userService.resetBlockMutationsForTesting();
        // Ghost-membership source: the in-memory member map keeps previous-spec users
        // "active" for the room-membership TTL even after the Gun graph is wiped.
        this.chatroomManager.resetForTesting();
        // The durable TechSupport store lives outside the relay's ephemeral Gun graph on
        // purpose (that's the whole point of it), so wiping `gun._.graph` above never touches
        // it — an explicit reset here is what keeps E2E specs isolated from each other.
        await this.techSupportStore.resetForTesting();
        await this.publishPublicBootstrap();
      },
      nodeEnv: process.env.NODE_ENV,
      ...(this.hubRelayClient ? { hubRelayClient: this.hubRelayClient } : {}),
      techSupportStore: this.techSupportStore,
    });

    registerUserRoutes(this.app, {
      userService: this.userService,
      ...(this.hubRelayClient ? { hubRelayClient: this.hubRelayClient } : {}),
    });

    registerTalkRoutes(this.app, {
      talkService: this.talkService,
      loadTalkDataFromGraphOrBody: this.loadTalkDataFromGraphOrBody.bind(this),
    });

    registerChatroomRoutes(this.app, {
      chatroomManager: this.chatroomManager,
      ...(this.hubRelayClient ? { hubRelayClient: this.hubRelayClient } : {}),
    });
    registerAdminRoutes(this.app, this.techSupportAnnouncements);

    registerStatsRoutes(this.app, {
      talkService: this.talkService,
      getBroadcastTagPopularity: () => this.broadcastTagPopularityStore.getSnapshot(),
      getBroadcastTagTrends: (days: number) => this.broadcastTagPopularityStore.getTrends(days),
    });

    registerMailboxRoutes(this.app, {
      mailboxStore: this.mailboxStore,
      techSupportStore: this.techSupportStore,
      nodeEnv: process.env.NODE_ENV,
    });

    registerTurnRoutes(this.app);
  }

  private setupSocketHandlers(): void {
    registerSocketHandlers(this.io, {
      chatroomManager: this.chatroomManager,
      talkService: this.talkService,
      userService: this.userService,
    });
  }

  public start(port: number = 8080): void {
    this.server.on('error', (err: NodeJS.ErrnoException) => {
      if (err.code === 'EADDRINUSE') {
        logger.fatal({ port }, `Port ${port} is already in use. Stop the other process or use a different PORT env var.`);
        process.exit(1);
      }
      throw err;
    });
    this.server.listen(port, () => {
      logger.info({ port, env: process.env.NODE_ENV || 'development' }, '🚀 IinPublic server started');
      const embedded = resolveEmbeddedNodeConfig(process.env);
      const lanDiscoveryExplicitlyEnabled = process.env.IINPUBLIC_LAN_DISCOVERY_ENABLED === '1';
      const lanDiscoveryEnabled = embedded.enabled
        ? process.env.IINPUBLIC_LAN_DISCOVERY_ENABLED !== '0'
        : lanDiscoveryExplicitlyEnabled;
      if (lanDiscoveryEnabled) {
        this.lanGunDiscovery = new LanGunDiscovery(this.gun, port);
        this.lanGunDiscovery.start();
      }
    });
    // Periodic mailbox sweep: evict expired envelopes every 5 minutes.
    this.mailboxSweepTimer = setInterval(() => {
      this.mailboxStore.pruneExpired();
    }, 5 * 60 * 1000);
    if (this.mailboxSweepTimer.unref) this.mailboxSweepTimer.unref();
  }
}

// Start server. Embedded mode (desktop/mobile) never reaches this — embedded-node.ts already
// does its own single `new IinPublicServer(); server.start(port)` after applying embedded env
// vars, and always sets IINPUBLIC_EMBEDDED_NODE=1 before this module ever runs. The extra check
// (not just `require.main === module`) matters once this module is bundled into a single file
// alongside embedded-node.ts (mobile's esbuild target, scripts/build-embedded-mobile.js): a
// bundler can collapse `require.main`/`module` identity across originally-separate source files,
// which made this guard fire a SECOND time on top of embedded-node.ts's own start call — two
// IinPublicServer instances racing to listen on the same port, crashing with EADDRINUSE.
if (require.main === module && process.env.IINPUBLIC_EMBEDDED_NODE !== '1') {
  const server = new IinPublicServer();
  const port = process.env.PORT ? parseInt(process.env.PORT) : 8080;
  server.start(port);
}

export default IinPublicServer;
