/**
 * MailboxStore — in-memory TTL store for encrypted offline mailbox envelopes.
 *
 * Design principles (spec §23.6 "Offline delivery"):
 * - The server NEVER sees plaintext. Envelopes hold only routing metadata + ciphertext.
 * - Envelopes are indexed by recipientId only (the only routing key the server needs).
 * - No Gun writes, no disk persistence — pure in-memory TTL store.
 * - Eviction is lazy (on access) + periodic sweep (via pruneExpired).
 *
 * Caps (chosen conservatively for a relay-only hub):
 *   DEFAULT_TTL_MS   = 48 h  (covers a weekend of offline time)
 *   MAX_TTL_MS       = 72 h  (hard ceiling; senders cannot request more)
 *   MAX_PER_RECIPIENT = 100  (prevents one offline user accumulating unbounded state)
 *   MAX_CIPHERTEXT_BYTES = 64 KiB (generous for SEA-encrypted mesh response payloads)
 *   MAX_TOTAL_ENVELOPES = 10_000 (global cap; oldest envelope evicted when exceeded)
 */

export const MAILBOX_DEFAULT_TTL_MS = 48 * 60 * 60 * 1000;   // 48 h
export const MAILBOX_MAX_TTL_MS     = 72 * 60 * 60 * 1000;   // 72 h
export const MAILBOX_MAX_PER_RECIPIENT = 100;
export const MAILBOX_MAX_CIPHERTEXT_BYTES = 64 * 1024;        // 64 KiB
export const MAILBOX_MAX_TOTAL_ENVELOPES = 10_000;

export type MailboxEnvelope = {
  /** UUID generated by the sender (dedup key on drain). */
  id: string;
  /** Opaque routing hint — the server does not interpret this. */
  recipientId: string;
  /** SEA ECDH ciphertext produced by the sender for the recipient's epub. */
  ciphertext: string;
  /** ISO timestamp when the envelope was stored. */
  createdAt: string;
  /** ISO timestamp when the envelope should be dropped (server-enforced). */
  expiresAt: string;
};

export type StoreEnvelopeResult =
  | { stored: true; envelope: MailboxEnvelope }
  | { stored: false; reason: string };

export class MailboxStore {
  /** recipientId → ordered list of envelopes (oldest first). */
  private readonly queues = new Map<string, MailboxEnvelope[]>();
  /** Total count across all recipients (fast global cap check). */
  private totalCount = 0;

  /**
   * Store an envelope for a recipient.
   *
   * Validation:
   * - ciphertext must be non-empty and within size cap.
   * - ttlMs is clamped to [1, MAX_TTL_MS]; defaults to DEFAULT_TTL_MS.
   * - Rejects if the per-recipient or global cap would be exceeded after eviction.
   *
   * Call pruneExpired() first (done inside store()) so caps are accurate.
   */
  store(params: {
    id: string;
    recipientId: string;
    ciphertext: string;
    ttlMs?: number;
    now?: Date;
  }): StoreEnvelopeResult {
    const now = params.now ?? new Date();
    this.pruneExpired(now);

    const { id, recipientId, ciphertext } = params;
    if (!id || typeof id !== 'string') return { stored: false, reason: 'id is required' };
    if (!recipientId || typeof recipientId !== 'string') return { stored: false, reason: 'recipientId is required' };
    if (!ciphertext || typeof ciphertext !== 'string') return { stored: false, reason: 'ciphertext is required' };
    if (Buffer.byteLength(ciphertext, 'utf8') > MAILBOX_MAX_CIPHERTEXT_BYTES) {
      return { stored: false, reason: `ciphertext exceeds ${MAILBOX_MAX_CIPHERTEXT_BYTES} byte limit` };
    }

    const ttlMs = Math.max(1, Math.min(params.ttlMs ?? MAILBOX_DEFAULT_TTL_MS, MAILBOX_MAX_TTL_MS));
    const expiresAt = new Date(now.getTime() + ttlMs).toISOString();
    const createdAt = now.toISOString();

    const queue = this.queues.get(recipientId) ?? [];

    // Dedup: reject if this envelope id is already stored (idempotent POST).
    if (queue.some((e) => e.id === id)) {
      const existing = queue.find((e) => e.id === id)!;
      return { stored: true, envelope: existing };
    }

    if (queue.length >= MAILBOX_MAX_PER_RECIPIENT) {
      return { stored: false, reason: 'per-recipient mailbox cap reached' };
    }
    if (this.totalCount >= MAILBOX_MAX_TOTAL_ENVELOPES) {
      // Global cap: evict the oldest envelope across all queues.
      this.evictOldestGlobal();
    }

    const envelope: MailboxEnvelope = { id, recipientId, ciphertext, createdAt, expiresAt };
    queue.push(envelope);
    this.queues.set(recipientId, queue);
    this.totalCount += 1;
    return { stored: true, envelope };
  }

  /**
   * List all non-expired envelopes for a recipient.
   * Calls pruneExpired() first so the returned list is always fresh.
   */
  list(recipientId: string, now?: Date): MailboxEnvelope[] {
    this.pruneExpired(now);
    return [...(this.queues.get(recipientId) ?? [])];
  }

  /**
   * Delete a single envelope by recipientId + envelopeId.
   * Returns true if the envelope was found and deleted, false if it was already gone.
   */
  delete(recipientId: string, envelopeId: string, now?: Date): boolean {
    this.pruneExpired(now);
    const queue = this.queues.get(recipientId);
    if (!queue) return false;
    const idx = queue.findIndex((e) => e.id === envelopeId);
    if (idx === -1) return false;
    queue.splice(idx, 1);
    this.totalCount -= 1;
    if (queue.length === 0) this.queues.delete(recipientId);
    return true;
  }

  /**
   * Remove all expired envelopes from every queue.
   * Called lazily on store/list/delete; also called by the periodic sweep timer.
   */
  pruneExpired(now: Date = new Date()): void {
    const ts = now.getTime();
    for (const [recipientId, queue] of this.queues) {
      const fresh = queue.filter((e) => new Date(e.expiresAt).getTime() > ts);
      const removed = queue.length - fresh.length;
      if (removed > 0) {
        this.totalCount -= removed;
        if (fresh.length === 0) this.queues.delete(recipientId);
        else this.queues.set(recipientId, fresh);
      }
    }
  }

  /** Diagnostic snapshot — total envelopes across all recipients. */
  getTotalCount(): number {
    return this.totalCount;
  }

  /** Diagnostic snapshot — per-recipient queue sizes. */
  getQueueSizes(): Record<string, number> {
    const out: Record<string, number> = {};
    for (const [id, q] of this.queues) out[id] = q.length;
    return out;
  }

  /**
   * Reset all state — used by E2E clear-database.
   */
  resetForTesting(): void {
    this.queues.clear();
    this.totalCount = 0;
  }

  // ── Private helpers ──────────────────────────────────────────────────────────

  private evictOldestGlobal(): void {
    let oldestTime = Infinity;
    let oldestRecipientId = '';
    for (const [recipientId, queue] of this.queues) {
      if (queue.length === 0) continue;
      const t = new Date(queue[0].createdAt).getTime();
      if (t < oldestTime) {
        oldestTime = t;
        oldestRecipientId = recipientId;
      }
    }
    if (!oldestRecipientId) return;
    const queue = this.queues.get(oldestRecipientId)!;
    queue.shift();
    this.totalCount -= 1;
    if (queue.length === 0) this.queues.delete(oldestRecipientId);
  }
}
